export { default as About } from './About';
export { default as Home } from './Home';
export { default as Contact } from './Contact';
export { default as Categories } from './Categories';
export { default as Login } from './Login';
export { default as SignUp } from './SignUp';
export { default as NotFound } from './NotFound';
export { default as MyAccount } from './MyAccount';
export { default as Pricing } from './Pricing';